
[build]
  base = "molly-strapi-backend"
  command = "npm run build"
  publish = "dist"
  functions = "molly-strapi-backend/functions"

[functions]
  included_files = ["!node_modules/better-sqlite3/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
